### ISSUE TITLE
Some details of speech recognition.

### ISSUE THREAD

**Issue by catqaq** [desh2608/gmm-hmm-asr#4]
Hi, thanks for your great job!
I am new to speech recognition, and would like to ask what the first dimension of input data feats represents? (Frame? State? Phoneme?) Then what does the hidden state of HMM represent? (Frame, state, phoneme?)

**Comment by desh2608** [comment]
Each input sample is a matrix of the form `frames x dim`. These are the acoustic observations processed through some STFT-like transform (such as log Mel filterbanks or MFCCs). The HMM is a generative model which assumes that there are underlying states which produce these frames, i.e., suppose you model an utterance using a 5-state  ergodic HMM, then the HMM is free to transition between these 5 states, and at each state, it emits a frame whose likelihood is given by the emission probability distribution of the HMM. Here we use a single Gaussian to model these emission probabilities.

**Comment by catqaq** [comment]
Thanks!
